[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
preview = true  # если хочешь включить новые проверки
select = ["E", "F", "I", "N", "B", "UP"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
